CREATE TABLE m_user(
    id BIGSERIAL PRIMARY KEY NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(256) NOT NULL,
    email VARCHAR(50) NOT NULL,
    status BOOLEAN DEFAULT TRUE,
    updated DATE NOT NULL DEFAULT CURRENT_DATE,
    created DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE m_category(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    created DATE NOT NULL DEFAULT CURRENT_DATE,
    updated DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE m_goods(
    id BIGSERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(50) NOT NULL,
    stock INT NOT NULL,
    category_id BIGINT REFERENCES m_category (id),
    user_id BIGINT REFERENCES m_user (id),
    status BOOLEAN DEFAULT TRUE,
    image_path VARCHAR(100) NOT NULL,
    created DATE NOT NULL DEFAULT CURRENT_DATE,
    updated DATE NOT NULL DEFAULT CURRENT_DATE
);