name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: e60ae5f9-139b-441c-b24d-763e6699f7d1
          heroku_app_name: warehousely-api
          heroku_email: gerin.rin@gmail.com
